# I use ~/.local/bin myself
local-bin-path: /home/patrick/.stack/bin

# Don't use system GHC and install as needed
system-ghc: false
install-ghc: true

templates:
  params:
    author-email: pbrisbin@gmail.com
    author-name: Pat Brisbin
    category: Network
    copyright: 2016 Pat Brisbin
    github-username: pbrisbin
