---
conf_version: 1

conf_errorHandling:
  # Attempt to exact-print unknown things
  econf_ExactPrintFallback: ExactPrintFallbackModeRisky

conf_layout:
  # 4-space indent, avoid context-aware anything
  lconfig_indentAmount: 4
  lconfig_indentPolicy: IndentPolicyLeft
  lconfig_columnAlignMode: {tag: ColumnAlignModeDisabled}

conf_preprocessor:
  # At least attempt to deal with CPP
  ppconf_CPPMode: CPPModeWarn
  ppconf_hackAroundIncludes: true
